# Generated by Django 2.1.7 on 2019-02-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_from', models.IntegerField()),
                ('date_to', models.IntegerField()),
                ('web_page', models.CharField(max_length=255, verbose_name='Web Page')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Building Name')),
                ('building_unit', models.CharField(blank=True, max_length=40, null=True, verbose_name='Building Unit')),
                ('place_name', models.CharField(max_length=255, verbose_name='Place Name')),
                ('post_code', models.CharField(max_length=20, verbose_name='Postcode')),
                ('street_name', models.CharField(max_length=255, verbose_name='Street Name')),
                ('street_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Street Number')),
                ('town', models.CharField(blank=True, max_length=20, null=True, verbose_name='Town')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Address'),
        ),
    ]
