# Generated by Django 2.1.7 on 2019-02-24 21:39

from django.db import migrations

json = [
    {
        "buildingUnit": "500",
        "buildingName": "Watermans House",
        "streetNumber": "21",
        "streetName": "New Village Agenue",
        "town": "London",
        "postcode": "E140GL"
    },
    {
        "buildingUnit": "4th Floor",
        "buildingName": '',
        "streetNumber": "9-10",
        "streetName": "Charterhouse Buildings",
        "town": "London",
        "postcode": "EC1M7AN"
    },
    {
        "buildingUnit": "Unit G.06",
        "buildingName": "Clerkenwell Workshops",
        "streetNumber": "27-31",
        "streetName": "Clerkenwell Close",
        "town": "London",
        "postcode": "EC1R0AT"
    }
]


def create_data(apps, schema_editor):
    Address = apps.get_model('activity', 'Address')
    for d in json:
        Address(buildingName=d['buildingName'],
                buildingUnit=d['buildingUnit'],
                placeName='',
                postcode=d['postcode'],
                streetName=d['streetName'],
                streetNumber=d['streetNumber'],
                town=d['town'],
                ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
