# Generated by Django 2.1.7 on 2019-02-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date_from',
            new_name='dateFrom',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date_to',
            new_name='dateTo',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='web_page',
            new_name='webPage',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='building_name',
            new_name='buildingName',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='building_unit',
            new_name='buildingUnit',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='place_name',
            new_name='placeName',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='post_code',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_name',
            new_name='streetName',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_number',
            new_name='streetNumber',
        ),
    ]
